app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls'), ),
    # path('votes/', include('apps.votes.urls'), ),
    path('tours_vote/', include('apps.tours_vote.urls'), ),
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView, LoginView

app_name = 'accounts'

urlpatterns = [
    path('', LoginView.as_view(template_name="login_page.html", redirect_authenticated_user=True), name="login", ),
    path('logout/', LogoutView.as_view(), name='logout'),
]

templates/_main.html
{% load static %}
<!DOCTYPE html>
<html lang="ru-ru" class="no-js" itemscope itemtype="https://schema.org/WebPage">
<head>
<meta name="theme-color" content="#003ba5">
<meta name="format-detection" content="telephone=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="/static/front/favicon.png">
<title>Голосование МГМСУ</title>
<meta name="description" content="Голосование конкурс МГМСУ" />
<link href="/static/front/stom.css" rel="stylesheet">
<script src="/static/front/stom.js"></script>
</head>
<body class="stom-background-primary" stom-height-viewport>

{% load widget_tweaks %}
{% if user.is_authenticated %}<div class="stom-section stom-section-primary">
<div class="stom-container stom-text-center stom-text-right@m">
   <a class="stom-button stom-button-primary" href="{% url "accounts:logout" %}" >Выход</a>
</div>
</div>
{% endif %}

{% block content %}

{% endblock %}
</body>
</html>

templates/login_page.html
 {% extends '_main.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="stom-section stom-preserve-color">
<div class="stom-container">
<div class="stom-grid">
<div class="stom-width-2-3@m"></div>
<div class="stom-width-1-3@m">
<div class="stom-card stom-card-default stom-card-body">
    <h1 class="stom-h3 stom-text-bolder">Вход в аккаунт</h1>
	<hr>
    <form method="post" action=".">
  {% csrf_token %}
     <div class="mui--text-danger">
    {% for error in form.non_field_errors %}
      {{error}}
    {% endfor %}
  </div>
      <div class="mui-textfield">
    <label class="stom-form-label">{{ form.username.label }}</label>
    {{ form.username|add_class:'stom-margin stom-input' }}
  </div>
  <div class="mui-textfield">
    <label class="stom-form-label">{{ form.password.label }}</label>
    {{ form.password|add_class:'stom-margin stom-input' }}
  </div>

  <input class="stom-button stom-button-primary" type="submit" value='Войти' />
    </form>
</div>
</div>
</div>
</div>	
 {% endblock %}